  AWSTemplateFormatVersion: '2010-09-09'
  Description: 'Setting up Service Discovery for two API end points.'
  Parameters:
    Region1HealthEndpoint:
      Description: The health endpoint in the first region.
      Type: String
      Default: h6ug5j0k02.execute-api.us-east-1.amazonaws.com
    Region2HealthEndpoint:
      Description: The health endpoint in the second region.
      Type: String
      Default: ywp3ygpun6.execute-api.us-west-2.amazonaws.com


  Resources:
    HealthcheckRegion1:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/prod/healthcheck"
          FullyQualifiedDomainName: !Ref Region1HealthEndpoint
          RequestInterval: "30"
          FailureThreshold: "2"

    HealthcheckRegion2:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/prod/healthcheck"
          FullyQualifiedDomainName: !Ref Region2HealthEndpoint
          RequestInterval: "30"
          FailureThreshold: "2"

