service: health-check-config

disabledDeprecations:
  - NESTED_CUSTOM_CONFIGURATION_PATH

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'prod'}

resources:
  Resources:
    HealthcheckRegion1:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/prod/health"
          FullyQualifiedDomainName: lo4p8e4zu2.execute-api.us-east-1.amazonaws.com
          RequestInterval: "30"
          FailureThreshold: "2"
        HealthCheckTags:
          - Key: Name
            Value: NorthVirginiaHealthCheck

    HealthcheckRegion2:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/prod/health"
          FullyQualifiedDomainName: x7n9hwtr8k.execute-api.us-west-2.amazonaws.com
          RequestInterval: "30"
          FailureThreshold: "2"
        HealthCheckTags:
          - Key: Name
            Value: OregonHealthCheck



