service: multiregion-logic-three

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
  apiName: multiregion-helloworld
  endpointType: REGIONAL

resources:
  Resources:
    HealthcheckRegion1:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/dev/health"
          FullyQualifiedDomainName: lo4p8e4zu2.execute-api.us-east-1.amazonaws.com
          RequestInterval: "30"
          FailureThreshold: "2"
        HealthCheckTags:
          - Key: Name
            Value: HealthcheckRegion1


    HealthcheckRegion2:
      Type: "AWS::Route53::HealthCheck"
      Properties:
        HealthCheckConfig:
          Port: "443"
          Type: "HTTPS_STR_MATCH"
          SearchString: "ok"
          ResourcePath: "/dev/health"
          FullyQualifiedDomainName: x7n9hwtr8k.execute-api.us-west-2.amazonaws.com
          RequestInterval: "30"
          FailureThreshold: "2"
        HealthCheckTags:
          - Key: Name
            Value: HealthcheckRegion2



